### ISSUE TITLE
Shortcut showing Hint before the last cloze after answering some cards.

### ISSUE THREAD

**Issue by huandney** [thiswillbeyourgithub/Oliver_Cloze#9] opened 2021-05-30 05:17 UTC
Hello friend, how long.
A strange error is occurring, after answering some cards, when showing the answer via the shortcut the tip is displayed immediately in the first cloze.
This does not happen if I click on the rectangle.
The curious thing is if I enter the editor and come back to answer, the error is fixed and the shortcut works perfectly.

![Error Certo](https://user-images.githubusercontent.com/19948348/120093215-b9f84a00-c0e6-11eb-8aaa-405f786486e3.gif)

**Comment by thiswillbeyourgithub** [comment] 2021-05-30 21:08
Hi, I took notice of your message but unfortunately am not able to take a look for a good while. I don't know when I'll take a look but you can try and remind me in at least a month if you care, otherwise I should eventually get to it in the summer :)

**Comment by huandney** [comment] 2021-05-30 23:52
No problem, I'll remind you. Thanks.

**Comment by thiswillbeyourgithub** [comment] 2021-06-10 10:16
Hey, can you remind me what anki version you are on?

I recently switched from 2.1.35 to 2.1.44 an adjusted a few things as the front card would not flip on its own. So you might be interested in testing the latest template if you're on 2.1.44. I'm not yet sure but I had to revert a few things so I think some old issue will re arise.

I contacted the devs about this and as long as I'm not sure this was a regression on their part (and will be fixed in the next anki) I prefer to avoid spending time fixing your issue as it could be related.

**Comment by huandney** [comment] 2021-06-10 13:33
What good news! It was at version 2.1.35.

I've updated here to version 2.1.44, everything apparently works fine except for the problem mentioned above.
The curious thing is that the first card we answer works as it should, the second one onwards always anticipates the "Hint" when we use the hotkey.
![Animação](https://user-images.githubusercontent.com/19948348/121533603-70550c80-c9ce-11eb-83d9-d7547feca06d.gif)

It seems that there is some residue from the first card that influences the next ones. If I go into the editor it corrects only for the first card.

**Comment by thiswillbeyourgithub** [comment] 2021-06-22 09:00
I just added a new line to the template to try and reset the c and n variable. Could you test it for me please? That would be helpful thanks.

**Comment by huandney** [comment] 2021-06-24 03:03
Hey,
~~Yesterday I had done a quick test and it seemed to work, but today the problem has returned, I will test it tomorrow for more times, but apparently the problem persists.~~

I thought it worked but I was actually triggering "let shortcutToHintWord" instead of "let shortcutToReveal", it's good to note that when we open it word for word it works as it should:

![Animação2](https://user-images.githubusercontent.com/19948348/123286696-2266fb00-d4dc-11eb-99de-3c09bdbf80f5.gif)

**Comment by huandney** [comment] 2022-01-15 19:17
Hi how long, any news? :)

**Comment by thiswillbeyourgithub** [comment] 2022-01-19 22:45
Hi, thanks for the reminder :)

I have encountered this issue myself several times but it seems to only happen after editing cards or undoing a review.

But I was never really bothered by it because I had tons of quick workarounds like undoing the review, pressing "d s <space>" to restart the review session and others that are only in my muscle memory.

I understand this seems ugly but in the end it never seemed to be a real problem. Is it really an issue for you? I don't think it's something easily fixable and javascript in anki is notoriously a pain to debug.

Another thing you could try are anking's latest notetypes. He made a video about them very recently and showed a very similar feature. Maybe it doens't have the same issue? I never tested it.

I would appreciated it if you could tell me if it works better if you decide to migrate :)

Btw I tested clozolkor on 2.1.49 and clozolkor still works fine besides this issue.

I'm closing this from the time being.

**Comment by huandney** [comment] 2022-01-21 04:09
Hi,
I've already tested anking notes and I think yours is a much superior version. he he
It bothers me a little, but no problem.
Thanks for this project, I'm also on 2.1.49, and it works great.

**Comment by huandney** [comment] 2022-02-03 21:09
Hey, @thiswillbeyourgithub 
I want to share with you a very interesting model that works very similar to native cloze.
I migrated my cards to this template, take a look:
https://drive.google.com/file/d/1qfxynpzzVNFSmCy-QVmSjTir4GorteFx/view?usp=sharing
Thank you so much for everything.

**Comment by thiswillbeyourgithub** [comment] 2022-02-04 11:39
Hey!

Thanks you VERY MUCH, this code seems very different from mine and will probably help me clean up mine!

Can you tell me where you found it?

**Comment by huandney** [comment] 2022-02-04 15:11
> Can you tell me where you found it?

Glad you liked it, I see you already found it.

**Closed as completed** 2022-02-04 15:54 UTC

**Comment by thiswillbeyourgithub** [comment] 2022-04-20 15:42
Found the dumb mistake and fixed it :)

b0ec64cd43c7da20042918d15eb0f2648c1f0c29

edit : unfortunately it seems to not fix all cases, the bug still exists :/ sorry!

edit: found another bug! This might be a full fix :)
